server:
  port: 8880
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    provider01: /p1/**
    consumer01: /c1/**
